wise-webapp/src/main/java/com/wisemapping/model/MindMapHistory.java
/*
*    Copyright [2015] [wisemapping]
*
*   Licensed under WiseMapping Public License, Version 1.0 (the "License").
*   It is basically the Apache License, Version 2.0 (the "License") plus the
*   "powered by wisemapping" text requirement on every single page;
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the license at
*
*       http://www.wisemapping.org/license
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package com.wisemapping.model;

import com.wisemapping.util.ZipUtils;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Calendar;

public class MindMapHistory {

    private int id;
    private Calendar creationTime;
    private User editor;
    private byte[] zippedXml;
    private int mindmapId;

    public MindMapHistory() {

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMindmapId() {
        return mindmapId;
    }

    public void setMindmapId(int id) {
        this.mindmapId = id;
    }

    @NotNull
    public Calendar getCreationTime() {
        return creationTime;
    }

    public void setCreationTime(Calendar creationTime) {
        this.creationTime = creationTime;
    }

    @Nullable
    public User getEditor() {
        return editor;
    }

    public void setEditor(@Nullable User editor) {
        this.editor = editor;
    }

    public byte[] getZippedXml() {
        return zippedXml;
    }

    public void setZippedXml(byte[] value) {
        zippedXml = value;
    }

    public byte[] getUnzipXml() throws IOException {
        return ZipUtils.zipToBytes(getZippedXml());
    }
}

wise-webapp/src/main/java/com/wisemapping/model/User.java
/*
*    Copyright [2015] [wisemapping]
*
*   Licensed under WiseMapping Public License, Version 1.0 (the "License").
*   It is basically the Apache License, Version 2.0 (the "License") plus the
*   "powered by wisemapping" text requirement on every single page;
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the license at
*
*       http://www.wisemapping.org/license
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package com.wisemapping.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.Serializable;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

public class User
        extends Collaborator
        implements Serializable {

    private String firstname;
    private String lastname;
    private String password;
    private long activationCode;
    private Calendar activationDate;
    private Set<String> tags = new HashSet<String>();
    private boolean allowSendEmail = false;
    private String locale;
    private AuthenticationType authenticationType;


    private String authenticatorUri;

    public User() {
    }

    public void setTags(Set<String> tags) {
        this.tags = tags;
    }

    public Set<String> getTags() {
        return tags;
    }

    public String getFullName() {
        return this.getFirstname() + " " + this.getLastname();
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isActive() {
        return activationDate != null;
    }

    public void setActivationCode(long code) {
        this.activationCode = code;
    }

    public long getActivationCode() {
        return activationCode;
    }

    public void setActivationDate(Calendar date) {
        this.activationDate = date;
    }

    public Calendar getActivationDate() {
        return activationDate;
    }

    public boolean isAllowSendEmail() {
        return allowSendEmail;
    }

    public void setAllowSendEmail(boolean allowSendEmail) {
        this.allowSendEmail = allowSendEmail;
    }

    @Nullable
    public String getLocale() {
        return locale;
    }

    public void setLocale(@Nullable String locale) {
        this.locale = locale;
    }

    public char getAutheticationTypeCode() {
        // Default authentication is database ....
        return this.authenticationType != null ? this.authenticationType.getCode() : AuthenticationType.DATABASE.getCode();
    }

    public void setAutheticationTypeCode(char code) {
        this.authenticationType = AuthenticationType.valueOf(code);
    }

    public AuthenticationType getAuthenticationType() {
        return authenticationType;
    }

    public void setAuthenticationType(@NotNull AuthenticationType authenticationType) {
        this.authenticationType = authenticationType;
    }

    public boolean isDatabaseSchema(){
        return this.authenticationType == AuthenticationType.DATABASE;
    }

    public String getAuthenticatorUri() {
        return authenticatorUri;
    }

    public void setAuthenticatorUri(String authenticatorUri) {
        this.authenticatorUri = authenticatorUri;
    }


}

wise-webapp/src/main/java/com/wisemapping/view/CollaboratorBean.java
/*
*    Copyright [2015] [wisemapping]
*
*   Licensed under WiseMapping Public License, Version 1.0 (the "License").
*   It is basically the Apache License, Version 2.0 (the "License") plus the
*   "powered by wisemapping" text requirement on every single page;
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the license at
*
*       http://www.wisemapping.org/license
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package com.wisemapping.view;

import com.wisemapping.model.CollaborationRole;
import com.wisemapping.model.Collaborator;
import com.wisemapping.model.User;

public class CollaboratorBean {
    private CollaborationRole collaborationRole;
    private boolean isUser;
    private Collaborator collaborator;

    public CollaboratorBean(Collaborator collaborator, CollaborationRole role) {
        this.collaborator = collaborator;
        this.collaborationRole = role;
        this.isUser = false;
    }

    public CollaboratorBean(User user, CollaborationRole role) {
        this.collaborator = user;
        this.collaborationRole = role;
        this.isUser = true;
    }

    public boolean isUser() {
        return isUser;
    }

    public String getRole() {
        return collaborationRole.name();
    }

    public String getUsername() {
        return isUser ? ((User) collaborator).getFullName() : collaborator.getEmail();
    }

    public String getEmail() {
        return collaborator.getEmail();
    }

    public long getId() {
        return collaborator.getId();
    }
}

wise-webapp/src/main/java/com/wisemapping/view/MindMapBean.java
/*
*    Copyright [2015] [wisemapping]
*
*   Licensed under WiseMapping Public License, Version 1.0 (the "License").
*   It is basically the Apache License, Version 2.0 (the "License") plus the
*   "powered by wisemapping" text requirement on every single page;
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the license at
*
*       http://www.wisemapping.org/license
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package com.wisemapping.view;

import com.wisemapping.exceptions.AccessDeniedSecurityException;
import com.wisemapping.exceptions.WiseMappingException;
import com.wisemapping.model.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class MindMapBean {
    private Mindmap mindmap;
    private List<CollaboratorBean> viewers;
    private List<CollaboratorBean> collaborators;
    private Collaborator collaborator;

    public MindMapBean(@NotNull final Mindmap mindmap, @Nullable final Collaborator collaborator) {
        this.mindmap = mindmap;
        this.collaborator = collaborator;
        this.collaborators = filterCollaboratorBy(mindmap.getCollaborations(), CollaborationRole.EDITOR);
        this.viewers = filterCollaboratorBy(mindmap.getCollaborations(), CollaborationRole.VIEWER);
    }

    public boolean getPublic() {
        return mindmap.isPublic();
    }

    public String getTitle() {
        return mindmap.getTitle();
    }

    public String getDescription() {
        return mindmap.getDescription();
    }

    public int getId() {
        return mindmap.getId();
    }

    public boolean isStarred() {
        return mindmap.isStarred(collaborator);
    }

    public List<CollaboratorBean> getViewers() {
        return viewers;
    }

    public List<CollaboratorBean> getCollaborators() {
        return collaborators;
    }

    public String getLastEditor() {
        final User lastEditor = mindmap.getLastEditor();
        return lastEditor != null ? lastEditor.getFullName() : "";
    }

    public String getLastEditTime() {
        return DateFormat.getInstance().format(mindmap.getLastModificationTime().getTime());
    }

    public String getCreationTime() {
        return DateFormat.getInstance().format(mindmap.getCreationTime().getTime());
    }

    public String getTags() {
        return mindmap.getTags();
    }

    private List<CollaboratorBean> filterCollaboratorBy(Set<Collaboration> source, CollaborationRole role) {
        List<CollaboratorBean> col = new ArrayList<CollaboratorBean>();
        if (source != null) {
            for (Collaboration mu : source) {
                if (mu.getRole() == role) {
                    col.add(new CollaboratorBean(mu.getCollaborator(), mu.getRole()));
                }
            }
        }
        return col;
    }

    public int getCountCollaborators() {
        return collaborators != null ? collaborators.size() : 0;
    }

    public int getCountViewers() {
        return viewers != null ? viewers.size() : 0;
    }

    public int getCountShared() {
        return getCountCollaborators() + getCountViewers();
    }

    public boolean isShared() {
        return getCountShared() > 0;
    }

    public void setTitle(String t) {
        mindmap.setTitle(t);
    }

    public void setDescription(String d) {
        mindmap.setDescription(d);
    }

    public String getXmlAsJsLiteral() throws IOException {
        return this.mindmap.getXmlAsJsLiteral();
    }

    public String getProperties() throws WiseMappingException {
        String result = null;

        if (collaborator != null) {
            try {
                final CollaborationProperties properties = this.mindmap.findCollaborationProperties(collaborator);
                result = properties.getMindmapProperties();
            } catch (AccessDeniedSecurityException e) {
                // Ignore exception. This is required for the admin could view maps ...
            }
        }

        if (result == null) {
            // It must be public view ...
            result = CollaborationProperties.DEFAULT_JSON_PROPERTIES;
        }

        return result;
    }

    public User getCreator() {
        return mindmap.getCreator();
    }

    public boolean isOwner() {
        return mindmap.hasPermissions(collaborator, CollaborationRole.OWNER);
    }

    public boolean isEditor() {
        return mindmap.hasPermissions(collaborator, CollaborationRole.EDITOR);
    }

    public String getRole() {
        final Collaboration collaboration = this.mindmap.findCollaboration(collaborator);
        return collaboration.getRole().getLabel();
    }


    public Mindmap getDelegated() {
        return mindmap;
    }

}

wise-webapp/src/main/java/com/wisemapping/webmvc/LoginController.java
/*
*    Copyright [2015] [wisemapping]
*
*   Licensed under WiseMapping Public License, Version 1.0 (the "License").
*   It is basically the Apache License, Version 2.0 (the "License") plus the
*   "powered by wisemapping" text requirement on every single page;
*   you may not use this file except in compliance with the License.
*   You may obtain a copy of the license at
*
*       http://www.wisemapping.org/license
*
*   Unless required by applicable law or agreed to in writing, software
*   distributed under the License is distributed on an "AS IS" BASIS,
*   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*   See the License for the specific language governing permissions and
*   limitations under the License.
*/

package com.wisemapping.webmvc;

import com.wisemapping.model.User;
import com.wisemapping.security.Utils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class LoginController {

    @Value("${database.driver}")
    private String driver;

    @RequestMapping(value = "login", method = RequestMethod.GET)
    protected ModelAndView showLoginPage() {
        final User user = Utils.getUser(false);
        ModelAndView result;
        if (user != null) {
            result = new ModelAndView("forward:/c/maps/");
        } else {
            result = new ModelAndView("login");
            result.addObject("isHsql", driver.contains("hsql"));
        }
        return result;
    }

    @RequestMapping(value = "loginopenid", method = RequestMethod.GET)
    protected ModelAndView showLoginOpenIdPage() {
        final User user = Utils.getUser(false);
        ModelAndView result;
        if (user != null) {
            result = new ModelAndView("forward:/c/maps/");
        } else {
            result = new ModelAndView("loginopenid");
        }
        return result;
    }

}

wise-webapp/src/main/webapp/jsp/browserNotSupported.jsp
<%@page pageEncoding="UTF-8" %>
<%@include file="/jsp/init.jsp" %>

<h2><spring:message code="BROWSER_NOT_SUPPORTED_TITLE"/></h2>

<p><spring:message code="BROWSER_NOT_SUPPORTED_MSG"/></p>
<ul>
    <li>Chrome 19 <spring:message code="OR_GREATER"/></li>
    <li>Firefox 11.0 <spring:message code="OR_GREATER"/></li>
    <li>Opera 11 <spring:message code="OR_GREATER"/></li>
    <li>Safari 5 <spring:message code="OR_GREATER"/></li>
    <li>Internet Explorer 8.0 <spring:message code="OR_GREATER"/></li>
</ul>
<p>
    <spring:message code="BROWSER_NOT_SUPPORTED_TRY_AGAIN"/>
</p>

<p>
    <span class="label label-info"><spring:message code="IMPORTANT"/>: </span><spring:message
        code="BROWSER_RECOMMENDATION"/>
</p>

wise-webapp/src/main/webapp/jsp/dialogTemplate.jsp
<%@page pageEncoding="UTF-8" %>
<%@include file="/jsp/init.jsp" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>

<!DOCTYPE HTML>

<tiles:importAttribute name="title" scope="page"/>
<tiles:importAttribute name="details" scope="page"/>
<html>
<head>
</head>
<body>
<div>
    <tiles:insertAttribute name="body"/>
</div>
</body>
</html>

wise-webapp/src/main/webapp/jsp/errorTemplate.jsp
<!DOCTYPE HTML>

<%@ page autoFlush="true" buffer="none" %>
<%@ include file="/jsp/init.jsp" %>

<h2>
    <spring:message code="${requestScope.title}"/>
</h2>

<strong>
    <spring:message code="${requestScope.details}"/>
</strong>

wise-webapp/src/main/webapp/jsp/mindmapDetail.jsp
<%@page pageEncoding="UTF-8" %>
<%@include file="/jsp/init.jsp" %>
<%--@elvariable id="mindmap" type="com.wisemapping.view.MindMapBean"--%>

<div>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#general" data-toggle="pill"><spring:message code="DESCRIPTION"/></a></li>
        <li><a href="#collaborators" data-toggle="pill"><spring:message code="SHARED"/></a></li>
        <li><a href="#publish" data-toggle="pill"><spring:message code="PUBLIC"/></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade active in" id="general">
            <ul class="unstyled">
                <li><strong><spring:message code="NAME"/>:</strong> <c:out value="${mindmap.title}"/></li>
                <li><strong><spring:message code="DESCRIPTION"/>:</strong> <c:out value="${mindmap.description}"/></li>
                <li><strong><spring:message code="CREATOR"/>:</strong> <c:out value="${mindmap.creator.fullName}"/></li>
                <li><strong><spring:message code="CREATION_TIME"/>:</strong> ${mindmap.creationTime}</li>
                <li><strong><spring:message code="LAST_UPDATE"/>:</strong> ${mindmap.lastEditTime}</li>
                <li><strong><spring:message code="LAST_UPDATE_BY"/>:</strong> <c:out value="${mindmap.lastEditor}"/>
                </li>
                <li><strong> <spring:message code="STARRED"/>:</strong> ${mindmap.starred}</li>
            </ul>
        </div>
        <div class="tab-pane fade" id="collaborators">
            <ul class="unstyled">
                <li>
                    <strong><spring:message code="YOUR_ROLE"/></strong>: ${mindmap.role}
                </li>
                <c:if test="${mindmap.owner}">
                    <li><strong><spring:message
                            code="EDITORS"/>(${mindmap.countCollaborators}): </strong>
                        <c:forEach items="${mindmap.collaborators}" var="mindmapCollaborator">
                            ${mindmapCollaborator.username}
                        </c:forEach>
                    </li>
                    <li><strong><spring:message code="VIEWERS"/>(${mindmap.countViewers}): </strong>
                        <c:forEach items="${mindmap.viewers}" var="mindmapViewer">
                            ${mindmapViewer.username}
                        </c:forEach>
                    </li>
                </c:if>
            </ul>
        </div>

        <div class="tab-pane fade" id="publish">
            <c:choose>
                <c:when test="${mindmap.public}">
                    <ul class="unstyled">
                        <p><spring:message code="ALL_VIEW_PUBLIC"/></p>
                        <li><strong><spring:message code="DIRECT_LINK_EXPLANATION"/></strong>
                        <li><input name="url"
                                   value="${baseUrl}/c/maps/${mindmap.id}/public"
                                   style="width:400px;cursor: text" readonly="readonly"/>
                        </li>
                        <li><strong><spring:message code="BLOG_SNIPPET"/></strong>
                            <pre>&lt;iframe style="border:0;width:600px;height:400px;border: 1px solid black" src="${baseUrl}/c/maps/${mindmap.id}/embed?zoom=1"&gt;&lt;/iframe&gt;</pre>
                        </li>
                        <li><spring:message code="EMBEDDED_MAP_SIZE"/></li>
                    </ul>

                </c:when>
                <c:otherwise>
                    <p><spring:message code="ONLY_VIEW_PRIVATE"/></p>
                </c:otherwise>
            </c:choose>
        </div>
    </div>
</div>

wise-webapp/src/main/webapp/jsp/mindmapEditor.jsp
<%@ page import="com.wisemapping.security.Utils" %>
<%@ page import="com.wisemapping.model.User" %>
<%@ page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/jsp/init.jsp" %>

<!DOCTYPE HTML>

<%--@elvariable id="mindmap" type="com.wisemapping.model.Mindmap"--%>
<%--@elvariable id="editorTryMode" type="java.lang.Boolean"--%>
<%--@elvariable id="editorTryMode" type="java.lang.String"--%>
<%--@elvariable id="lockInfo" type="com.wisemapping.service.LockInfo"--%>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <base href="${requestScope['site.baseurl']}/">
    <title><spring:message code="SITE.TITLE"/> - <c:out value="${mindmap.title}"/></title>
    <!--[if lt IE 9]>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <![endif]-->
    <link rel="stylesheet/less" type="text/css" href="css/editor.less"/>
    <script type='text/javascript' src='js/jquery.js'></script>
    <script type='text/javascript' src='js/jquery-mousewheel.js'></script>
    <script type='text/javascript' src='js/hotkeys.js'></script>
    <script type='text/javascript' src='js/underscorejs.js'></script>
    <script type='text/javascript' src='bootstrap/js/bootstrap.min.js'></script>
    <script type='text/javascript' src='js/mootools-core.js'></script>
    <script type='text/javascript' src='js/core.js'></script>
    <script type='text/javascript' src='js/less.js'></script>

    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

    <script type="text/javascript">

        $(document).on('loadcomplete', function (resource) {
            try {
                var mapId = '${mindmap.id}';
                // Configure designer options ...
                var options = loadDesignerOptions();

            <c:if test="${!memoryPersistence && !readOnlyMode}">
                options.persistenceManager = new mindplot.RESTPersistenceManager(
                        {
                            documentUrl:"c/restful/maps/{id}/document",
                            revertUrl:"c/restful/maps/{id}/history/latest",
                            lockUrl:"c/restful/maps/{id}/lock",
                            timestamp: "${lockTimestamp}",
                            session: "${lockSession}"
                        }
                );
            </c:if>
            <c:if test="${memoryPersistence || readOnlyMode}">
                options.persistenceManager = new mindplot.LocalStorageManager("c/restful/maps/{id}${hid!=null?'/':''}${hid!=null?hid:''}/document/xml${principal!=null?'':'-pub'}",true);
            </c:if>

                var userOptions = ${mindmap.properties};
                options.zoom = userOptions.zoom;
                options.readOnly = ${!!readOnlyMode};
                options.locale = '${locale}';

                // Set map id ...
                options.mapId = mapId;

                // Build designer ...
                var designer = buildDesigner(options);

                // Load map from XML file persisted on disk...
                var persistence = mindplot.PersistenceManager.getInstance();
                var mindmap = mindmap = persistence.load(mapId);
                designer.loadMap(mindmap);

            } catch (e) {
                logStackTrace(e);
                throw e;
            }

            <c:if test="${mindmapLocked}">
            $notify("<spring:message code="MINDMAP_LOCKED" arguments="${lockInfo.user.fullName},${lockInfo.user.email}"/>", false);
            </c:if>
        });


    </script>
    <%@ include file="/jsp/googleAnalytics.jsf" %>
</head>
<body>

<div id="actionsContainer"></div>

<div id="header">
    <div id="headerInfo">
        <div id="headerActions">
            <c:if test="${!memoryPersistence}">

                <spring:message code="WELCOME"/>, ${principal.firstname} |
                <span><a href="c/maps/"><spring:message code="MY_WISEMAPS"/></a></span> |
                <span><a href="#" target=" " id="tutorialVideo"><spring:message code="TUTORIAL_VIDEO"/></a></span> |
                <span><a href="c/keyboard" id="keyboardShortcuts"><spring:message code="SHORTCUTS"/></a></span> |
                <span><a href="c/logout" title="<spring:message code="LOGOUT"/>"><spring:message
                        code="LOGOUT"/></a></span>
            </c:if>
            <c:if test="${memoryPersistence}">
                <span><a href="c/keyboard" id="tutorialVideo"><spring:message code="TUTORIAL_VIDEO"/></a></span> |
                <span><a href="#" id="keyboardShortcuts"><spring:message code="SHORTCUTS"/></a></span> |
                <span><a href="c/user/registration" title="<spring:message code="REGISTER"/>"><spring:message
                        code="REGISTER"/></a></span>
            </c:if>
        </div>
        <a href="${requestScope['site.homepage']}">
            <div id="headerLogo"></div>
        </a>

        <div id="headerMapTitle"><spring:message code="NAME"/>: <span><c:out value="${mindmap.title}"/></span></div>
    </div>
    <%@ include file="/jsp/mindmapEditorToolbar.jsf" %>
</div>

<div id='load' class="modal fade">
    <div class="modal-dialog">
        <div style="height: 120px; text-align: center; border: 2px solid orange" class="modal-content">
            <img style='margin-top:25px; text-align: center' src="images/ajax-loader.gif">
        </div>
    </div>
</div>

<div id="mindplot" onselectstart="return false;"></div>
<script type="text/javascript" src="js/editor.js"></script>
</body>
</html>

wise-webapp/src/main/webapp/jsp/mindmapEmbed.jsp
<%@page pageEncoding="UTF-8" %>
<%@include file="/jsp/init.jsp" %>

<!DOCTYPE HTML>

<%--@elvariable id="mindmap" type="com.wisemapping.model.Mindmap"--%>
<%--@elvariable id="editorTryMode" type="java.lang.Boolean"--%>
<%--@elvariable id="editorTryMode" type="java.lang.String"--%>


<html>
<head>
    <base href="${requestScope['site.baseurl']}/">
    <title><spring:message code="SITE.TITLE"/> - ${mindmap.title} </title>

    <!--[if lt IE 9]>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <![endif]-->

    <link rel="stylesheet/less" type="text/css" href="css/embedded.less"/>
    <script type='text/javascript' src='js/jquery.js'></script>
    <script type='text/javascript' src='js/jquery-mousewheel.js'></script>
    <script type='text/javascript' src='js/hotkeys.js'></script>
    <script type='text/javascript' src='js/underscorejs.js'></script>
    <script type='text/javascript' src='bootstrap/js/bootstrap.min.js'></script>
    <script type='text/javascript' src='js/mootools-core.js'></script>
    <script type='text/javascript' src='js/core.js'></script>
    <script type='text/javascript' src='js/less.js'></script>


    <script type="text/javascript">
        var mapId = '${mindmap.id}';

        $(document).on('loadcomplete', function (resource) {

            // Configure designer options ...
            var options = loadDesignerOptions();
            options.size.height = options.size.height + 50;
            options.locale = '${locale}';


            var userOptions = ${mindmap.properties};
            options.zoom = ${zoom};

            // Set map id ...
            options.mapId = mapId;

            // Print is read only ...
            options.readOnly = true;

            // Configure persistence ...
            options.persistenceManager = new mindplot.LocalStorageManager("c/restful/maps/{id}/document/xml${principal!=null?'':'-pub'}",true);

            // Build designer ...
            var designer = buildDesigner(options);

            // Load map ...
            var persistence = mindplot.PersistenceManager.getInstance();
            var mindmap = mindmap = persistence.load(mapId);
            designer.loadMap(mindmap);

            $('zoomIn').addEvent('click', function () {
                designer.zoomIn();
            });

            $('zoomOut').addEvent('click', function () {
                designer.zoomOut();
            });
        });
    </script>
</head>
<body>
<div id="mapContainer">
    <div id="mindplot" onselectstart="return false;"></div>

    <div id="embFooter">
        <a href="${requestScope['site.homepage']}" target="new">
            <div id="footerLogo"></div>
        </a>

        <div id="zoomIn" class="button"></div>
        <div id="zoomOut" class="button"></div>

        <div id="mapDetails">
            <span class="title"><spring:message code="CREATOR"/>:</span><span><c:out value="${mindmap.creator.fullName}"/></span>
            <span class="title"><spring:message code="DESCRIPTION"/>:</span><span><c:out value="${mindmap.title}"/></span>
        </div>
    </div>
</div>
<script type="text/javascript" src="js/editor.js"></script>
<%@ include file="/jsp/googleAnalytics.jsf" %>
</body>
</html>

wise-webapp/src/main/webapp/jsp/userForgotPasswordError.jsp
<%@page pageEncoding="UTF-8" %>
<%@include file="/jsp/init.jsp" %>

<h2><spring:message code="ACCOUNT_DOES_NOT_EXISTS"/></h2>

<p><spring:message code="ACCOUNT_DOES_NOT_EXISTS_SUPPORT"/></p>